
# Common web mime types
BASE_MIMES = {
	'bin':    'application/octet-stream',
	'mov':    'video/quicktime',
	'aac':    'audio/aac',
	'abw':    'application/x-abiword',
	'arc':    'application/x-freearc',
	'avif':   'image/avif',
	'avi':    'video/x-msvideo',
	'azw':    'application/vnd.amazon.ebook',
	'bmp':    'image/bmp',
	'bz':     'application/x-bzip',
	'bz2':    'application/x-bzip2',
	'cda':    'application/x-cdf',
	'csh':    'application/x-csh',
	'css':    'text/css',
	'csv':    'text/csv',
	'doc':    'application/msword',
	'docx':   'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'eot':    'application/vnd.ms-fontobject',
	'epub':   'application/epub+zip',
	'gz':     'application/gzip',
	'gif':    'image/gif',
	'htm':    'text/html',
	'html':   'text/html',
	'ico':    'image/vnd.microsoft.icon',
	'ics':    'text/calendar',
	'jar':    'application/java-archive',
	'jpeg':   'image/jpeg',
	'jfif':   'image/jpeg',
	'jpg':    'image/jpeg',
	'js':     'text/javascript',
	'json':   'application/json',
	'jsonld': 'application/ld+json',
	'mid':    'audio/midi audio/x-midi',
	'midi':   'audio/midi audio/x-midi',
	'mjs':    'text/javascript',
	'mp3':    'audio/mpeg',
	'mp4':    'video/mp4',
	'mpeg':   'video/mpeg',
	'mpkg':   'application/vnd.apple.installer+xml',
	'odp':    'application/vnd.oasis.opendocument.presentation',
	'ods':    'application/vnd.oasis.opendocument.spreadsheet',
	'odt':    'application/vnd.oasis.opendocument.text',
	'oga':    'audio/ogg',
	'ogv':    'video/ogg',
	'ogx':    'application/ogg',
	'opus':   'audio/opus',
	'otf':    'font/otf',
	'png':    'image/png',
	'apng':   'image/apng',
	'pdf':    'application/pdf',
	'php':    'application/x-httpd-php',
	'ppt':    'application/vnd.ms-powerpoint',
	'pptx':   'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	'rar':    'application/vnd.rar',
	'rtf':    'application/rtf',
	'sh':     'application/x-sh',
	'svg':    'image/svg+xml',
	'tar':    'application/x-tar',
	'tif':    'image/tiff',
	'tiff':   'image/tiff',
	'ts':     'video/mp2t',
	'ttf':    'font/ttf',
	'txt':    'text/plain',
	'vsd':    'application/vnd.visio',
	'wav':    'audio/wav',
	'weba':   'audio/webm',
	'webm':   'video/webm',
	'webp':   'image/webp',
	'woff':   'font/woff',
	'woff2':  'font/woff2',
	'xhtml':  'application/xhtml+xml',
	'xls':    'application/vnd.ms-excel',
	'xlsx':   'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	'xml':    'application/xml',
	'xul':    'application/vnd.mozilla.xul+xml',
	'zip':    'application/zip',
	'3gp':    'video/3gpp; audio/3gpp',
	'3g2':    'video/3gpp2; audio/3gpp2',
	'7z':     'application/x-7z-compressed',
}

# Same, but with with '.' prefix in file extensions
BASE_MIMES_SIGNED = {
	('.'+key):value for (key,value) in BASE_MIMES.items()
}

BASE_MIMES_PREFIXED = BASE_MIMES_SIGNED


RSP_CODE_MAP = {
	# Information responses
	100: '100 Continue',
	101: '101 Switching Protocols',
	102: '102 Processing',
	103: '103 Early Hints',

	# Successful responses
	200: '200 OK',
	201: '201 Created',
	202: '202 Accepted',
	203: '203 Non-Authoritative Information',
	204: '204 No Content',
	205: '205 Reset Content',
	206: '206 Partial Content',
	207: '207 Multi-Status',
	208: '208 Already Reported',
	226: '226 IM Used',

	# Redirection messages
	300: '300 Multiple Choices',
	301: '301 Moved Permanently',
	302: '302 Found',
	303: '303 See Other',
	304: '304 Not Modified',
	307: '307 Temporary Redirect',
	308: '308 Permanent Redirect',

	# Client error responses
	400: '400 Bad Request',
	401: '401 Unauthorized',
	402: '402 Payment Required',
	403: '403 Forbidden',
	404: '404 Not Found',
	405: '405 Method Not Allowed',
	406: '406 Not Acceptable',
	407: '407 Proxy Authentication Required',
	408: '408 Request Timeout',
	409: '409 Conflict',
	410: '410 Gone',
	411: '411 Length Required',
	412: '412 Precondition Failed',
	413: '413 Payload Too Large',
	414: '414 URI Too Long',
	415: '415 Unsupported Media Type',
	416: '416 Range Not Satisfiable',
	417: '417 Expectation Failed',
	418: """418 I'm a teapot""",
	421: '421 Misdirected Request',
	422: '422 Unprocessable Content',
	423: '423 Locked',
	424: '424 Failed Dependency',
	425: '425 Too Early',
	426: '426 Upgrade Required',
	428: '428 Precondition Required',
	429: '429 Too Many Requests',
	431: '431 Request Header Fields Too Large',
	451: '451 Unavailable For Legal Reasons',

	# Server error responses
	500: '500 Internal Server Error',
	501: '501 Not Implemented',
	502: '502 Bad Gateway',
	503: '503 Service Unavailable',
	504: '504 Gateway Timeout',
	505: '505 HTTP Version Not Supported',
	506: '506 Variant Also Negotiates',
	507: '507 Insufficient Storage',
	508: '508 Loop Detected',
	510: '510 Not Extended',
	511: '511 Network Authentication Required',
}

